on: issues
name: Issue triage
jobs:
  applyTriageLabel:
    name: Apply Triage Label
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Apply Triage Label
      uses: actions/github@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: label needs-triage --action=opened
